default_context:
    author_name: "Eva Maxfield Brown"
    author_email: "evamaxfieldbrown@gmail.com"
    hosting_github_username_or_org: "evamaxfield"
    project_name: "evaplot"
    project_slug: "evaplot"
    python_slug: "evaplot"
    project_short_description: "An up-to-date and slimmed down library for opinionated plotting styles with seaborn and matplotlib"